---
name: postgres
instance_groups:
- name: bosh
  azs: [z1]
  instances: 1
  jobs:
  - {name: postgres-9.4, release: bosh}
  vm_type: default
  stemcell: default
  persistent_disk_type: default
  networks:
  - name: default
  properties:
    postgres:
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: c1oudc0w
      database: bosh
      adapter: postgres

stemcells:
- alias: default
  os: ((stemcell-os))
  version: latest

releases:
- name: bosh
  version: "264.7.0"
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=264.7.0
  sha1: 11433d7530eea34d9ae2385ce2a7cb13912928bf

update:
  canaries: 1
  max_in_flight: 10
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
