---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: dpb587/metalink-repository-resource

inputs:
- name: candidate-version
- name: metalink-path
- name: compiled-release

params:
  AWS_ACCESS_KEY_ID: ((bosh-compiled-releases-aws-access-key-id))
  AWS_SECRET_ACCESS_KEY: ((bosh-compiled-releases-aws-secret-access-key))
  git_private_key: ((bosh-compiled-releases-index-deploy-key))

run:
  path: bosh-src/ci/tasks/push-bosh-compiled-release.sh
