---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bosh-src
  - name: stemcell
  - name: bosh-release
  - name: database-metadata
    optional: true
  - name: gcp-ssl-config
    optional: true

run:
  path: bosh-src/ci/tasks/test-bbr.sh

params:
  FOCUS_SPEC: ""
  STEMCELL_OS: ""
